name: cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish --no-self-contained --runtime linux-x64 --configuration Release --output ./artifact/publish ./templates/T1cloudformation.yaml

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r ../src.zip .
      working-directory: artifact/publish

    - uses: actions/upload-artifact@v3
      with:
        name: src
        path: ./artifact

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_TEAM1_CICD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_TEAM1_CICD_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Upload to AWS
      run: aws src cp ./artifact/src.zip src://rawt3data








